---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title: San Francisco Magician
keywords: "magician, San Francisco, bay area, Robert Strong, magic, wand, comedy, comedian, juggling, juggler, escapes, escape artist, pick-pocketing, pick-pocket, mind reading, mind reader, perform, event, venues, entertaining, About, Shows, photos, video, contact"
description: "The San Francisco Magician, his Bay Area shows, videos, venues, and how to hire him!"
google_analytics_key: UA-54865607-1


### template colors, used site-wide via css ###
colors:
  black:
    light: '#303030'
    dark: '#111111'
  white:
    light: '#f5f5f5'
    dark: '#f8f8f8'
  blue:
    light: '#3c9eec'
    dark: '#49a7e9'
  green:
    light: '#a3d832'
    dark: '#9bcf2f'
  purple:
    light: '#c869bf'
    dark: '#c869bf'
  orange:
    light: '#faaf22'
    dark: '#fab125'
  turquoise:
    light: '#0fbfcf'
    dark: '#0fbfcf'
